version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    blossom:
      image: herearii/deep-oc-blossom
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    blossom-gpu:
      image: herearii/deep-oc-blossom:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    blossom-rclone:
      extends:
        service: blossom
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
